export const DEPARTMENT_DETAILS = {
  LOAD: `LOAD_DEPARTMENT_DETAILS`,
  LOAD_SUCCESS: `LOAD_DEPARTMENT_DETAILS_SUCCESS`,
  LOAD_FAILURE: `LOAD_DEPARTMENT_DETAILS_FAILURE`,
  UNLOAD: `UNLOAD_DEPARTMENT_DETAILS`,
  UNLOAD_SUCCESS: `UNLOAD_DEPARTMENT_DETAILS_SUCCESS`,
  UNLOAD_FAILURE: `UNLOAD_DEPARTMENT_DETAILS_FAILURE`,
  PUT: `PUT_DEPARTMENT_DETAILS`,
  DELETE: `DELETE_DEPARTMENT`,
  DELETE_SUCCESS: `DELETE_DEPARTMENT_SUCCESS`,
  DELETE_FAILURE: `DELETE_DEPARTMENT_FAILURE`,
  SAVE_NEW: `SAVE_NEW_DEPARTMENT`,
  SAVE_NEW_SUCCESS: `SAVE_NEW_DEPARTMENT_SUCCESS`,
  SAVE_NEW_FAILURE: `SAVE_NEW_DEPARTMENT_FAILURE`
}
