export const EmployeesActionType = {
  LOAD_EMPLOYEES: `LOAD_EMPLOYEES`,
  LOAD_EMPLOYEES_SUCCESS: `LOAD_EMPLOYEES_SUCCESS`,
  LOAD_EMPLOYEES_FAILURE: `LOAD_EMPLOYEES_FAILURE`,
  LOAD_EMPLOYE_DETAILS: `LOAD_EMPLOYE_DETAILS`,
  LOAD_EMPLOYE_DETAILS_SUCCESS: `LOAD_EMPLOYE_DETAILS_SUCCESS`,
  LOAD_EMPLOYE_DETAILS_FAILURE: `LOAD_EMPLOYE_DETAILS_FAILURE`
}
