export const ActionType = {
  CHANGE_CITY: `CHANGE_CITY`,
  LOAD_OFFERS: `LOAD_OFFERS`,
  REQUIRE_AUTHORIZATION: `REQUIRE_AUTHORIZATION`,
  ADD_LOGIN: `ADD_LOGIN`,
  LOAD_REVIEWS: `LOAD_REVIEWS`,
  CHANGE_SORT: `CHANGE_SORT`
}
