export const EMPLOYE_DETAILS = {
  LOAD: `LOAD_EMPLOYE_DETAILS`,
  LOAD_SUCCESS: `LOAD_EMPLOYE_DETAILS_SUCCESS`,
  LOAD_FAILURE: `LOAD_EMPLOYE_DETAILS_FAILURE`,
  UPLOAD: `UPLOAD_EMPLOYE_DETAILS`,
  UPLOAD_SUCCESS: `UPLOAD_EMPLOYE_DETAILS_SUCCESS`,
  UPLOAD_FAILURE: `UPLOAD_EMPLOYE_DETAILS_FAILURE`
}
