export const EMPLOYE_DETAILS = {
  LOAD: `LOAD_EMPLOYE_DETAILS`,
  LOAD_SUCCESS: `LOAD_EMPLOYE_DETAILS_SUCCESS`,
  LOAD_FAILURE: `LOAD_EMPLOYE_DETAILS_FAILURE`,
  UNLOAD: `UNLOAD_EMPLOYE_DETAILS`,
  UNLOAD_SUCCESS: `UNLOAD_EMPLOYE_DETAILS_SUCCESS`,
  UNLOAD_FAILURE: `UNLOAD_EMPLOYE_DETAILS_FAILURE`
}
