export const EMPLOYE_DETAILS = {
  LOAD: `LOAD_EMPLOYE_DETAILS`,
  LOAD_SUCCESS: `LOAD_EMPLOYE_DETAILS_SUCCESS`,
  LOAD_FAILURE: `LOAD_EMPLOYE_DETAILS_FAILURE`,
  UNLOAD: `UNLOAD_EMPLOYE_DETAILS`,
  UNLOAD_SUCCESS: `UNLOAD_EMPLOYE_DETAILS_SUCCESS`,
  UNLOAD_FAILURE: `UNLOAD_EMPLOYE_DETAILS_FAILURE`,
  PUT: `PUT_EMPLOYE_DETAILS`,
  DELETE: `DELETE_EMPLOYE`,
  DELETE_SUCCESS: `DELETE_EMPLOYE_SUCCESS`,
  DELETE_FAILURE: `DELETE_EMPLOYE_FAILURE`,
  SAVE_NEW: `SAVE_NEW`,
  SAVE_NEW_SUCCESS: `SAVE_NEW_SUCCESS`,
  SAVE_NEW_FAILURE: `SAVE_NEW_FAILURE`
}
